caravan_employees = 35
caravan_resident = 'resident.lower'

caravan_base = {
	employees = caravan_employees,
	resident = caravan_resident,
	portrait = "images/ui/portrait/caravan/caravan_man.png",
}

atom ('hero.caravan.4', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
	},
})

atom ('hero.caravan.5', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
	},
})

atom ('hero.caravan.6', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
	},
})

atom ('hero.caravan.7', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
	},
})

atom ('hero.caravan.8', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
		'goods.ivory',
		'goods.ceremony',
		'goods.papyrus',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
		'walker.caravan.ivory',
		'walker.caravan.ceremony',
		'walker.caravan.papyrus',
	},
})

atom ('hero.caravan.9', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
		'goods.ivory',
		'goods.ceremony',
		'goods.papyrus',
		'goods.sheep',
		'goods.meat',
		'goods.wood',
		'goods.furniture',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
		'walker.caravan.ivory',
		'walker.caravan.ceremony',
		'walker.caravan.papyrus',
		'walker.caravan.sheep',
		'walker.caravan.meat',
		'walker.caravan.wood',
		'walker.caravan.furniture',
	},
})

atom ('hero.caravan.10', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
		'goods.ivory',
		'goods.ceremony',
		'goods.papyrus',
		'goods.sheep',
		'goods.meat',
		'goods.wood',
		'goods.furniture',
		'goods.gold',
		'goods.gold_jewels',
		'goods.stone',
		'goods.seal',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
		'walker.caravan.ivory',
		'walker.caravan.ceremony',
		'walker.caravan.papyrus',
		'walker.caravan.sheep',
		'walker.caravan.meat',
		'walker.caravan.wood',
		'walker.caravan.furniture',
		'walker.caravan.gold',
		'walker.caravan.gold_jewels',
		'walker.caravan.stone',
		'walker.caravan.seal',
	},
})

atom ('hero.caravan.11', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
		'goods.ivory',
		'goods.ceremony',
		'goods.papyrus',
		'goods.sheep',
		'goods.meat',
		'goods.wood',
		'goods.furniture',
		'goods.gold',
		'goods.gold_jewels',
		'goods.stone',
		'goods.seal',
		'goods.oil',
		'goods.flax',
		'goods.fabric',
		'goods.cloth',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
		'walker.caravan.ivory',
		'walker.caravan.ceremony',
		'walker.caravan.papyrus',
		'walker.caravan.sheep',
		'walker.caravan.meat',
		'walker.caravan.wood',
		'walker.caravan.furniture',
		'walker.caravan.gold',
		'walker.caravan.gold_jewels',
		'walker.caravan.stone',
		'walker.caravan.seal',
		'walker.caravan.oil',
		'walker.caravan.flax',
		'walker.caravan.fabric',
		'walker.caravan.cloth',
	},
})

atom ('hero.caravan.12', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
		'goods.ivory',
		'goods.ceremony',
		'goods.papyrus',
		'goods.sheep',
		'goods.meat',
		'goods.wood',
		'goods.furniture',
		'goods.gold',
		'goods.gold_jewels',
		'goods.stone',
		'goods.seal',
		'goods.oil',
		'goods.flax',
		'goods.fabric',
		'goods.cloth',
		'goods.dye',
		'goods.ceramic_luxury',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
		'walker.caravan.ivory',
		'walker.caravan.ceremony',
		'walker.caravan.papyrus',
		'walker.caravan.sheep',
		'walker.caravan.meat',
		'walker.caravan.wood',
		'walker.caravan.furniture',
		'walker.caravan.gold',
		'walker.caravan.gold_jewels',
		'walker.caravan.stone',
		'walker.caravan.seal',
		'walker.caravan.oil',
		'walker.caravan.flax',
		'walker.caravan.fabric',
		'walker.caravan.cloth',
		'walker.caravan.dye',
		'walker.caravan.ceramic_luxury',
	},
})

atom ('hero.caravan.13', caravan_base,
{
	goods = {
		'goods.wheat',
		'goods.bread',
		'goods.milk',
		'goods.clay',
		'goods.ceramic',
		'goods.brick',
		'goods.fish',
		'goods.dates',
		'goods.copper',
		'goods.copper_jewels',
		'goods.barley',
		'goods.beer',
		'goods.tablet',
		'goods.ivory',
		'goods.ceremony',
		'goods.papyrus',
		'goods.sheep',
		'goods.meat',
		'goods.wood',
		'goods.furniture',
		'goods.gold',
		'goods.gold_jewels',
		'goods.stone',
		'goods.seal',
		'goods.oil',
		'goods.flax',
		'goods.fabric',
		'goods.cloth',
		'goods.dye',
		'goods.ceramic_luxury',
		'goods.fleece',
		'goods.fabric_luxury',
		'goods.cloth_luxury',
		'goods.grapes',
		'goods.wine',
	},
	walkers = {
		'walker.caravan.wheat',
		'walker.caravan.bread',
		'walker.caravan.milk',
		'walker.caravan.clay',
		'walker.caravan.ceramic',
		'walker.caravan.brick',
		'walker.caravan.fish',
		'walker.caravan.dates',
		'walker.caravan.copper',
		'walker.caravan.copper_jewels',
		'walker.caravan.barley',
		'walker.caravan.beer',
		'walker.caravan.tablet',
		'walker.caravan.ivory',
		'walker.caravan.ceremony',
		'walker.caravan.papyrus',
		'walker.caravan.sheep',
		'walker.caravan.meat',
		'walker.caravan.wood',
		'walker.caravan.furniture',
		'walker.caravan.gold',
		'walker.caravan.gold_jewels',
		'walker.caravan.stone',
		'walker.caravan.seal',
		'walker.caravan.oil',
		'walker.caravan.flax',
		'walker.caravan.fabric',
		'walker.caravan.cloth',
		'walker.caravan.dye',
		'walker.caravan.ceramic_luxury',
		'walker.caravan.fleece',
		'walker.caravan.fabric_luxury',
		'walker.caravan.cloth_luxury',
		'walker.caravan.grapes',
		'walker.caravan.wine',
	},
})