-- Campaign level 13
atom('map_section.nz.sc.13', {
	map = "images/map_zoom.png",
	cities = {
		'base::city.nz.13.home',
		'city.nz.sc.13.assur',
		'city.nz.sc.13.ur',
		'city.nz.sc.13.damascus',
		'city.nz.sc.13.mendes',
		'city.nz.sc.13.thebes',
		'city.nz.sc.13.magan',
		'city.nz.sc.13.jerusalem',
		'city.nz.sc.13.aleppo',
		'city.nz.sc.13.kition',
		'city.nz.sc.13.ecbatana',
		'city.nz.sc.13.anshan',
	},
	
	cities_icon_positions = {
		{364, 359},
		{335, 223},
		{328, 207},
		{353, 366},
		{405, 400},
		{339, 740},
		{78, 321},
		{77, 359},
		{37, 260},
		{80, 202},
		{274, 180},
		{-79, 514},
	},
	cities_label_positions = {
		{320, 357},
		{380, 226},
		{375, 205},
		{310, 368},
		{367, 401},
		{337, 715},
		{108, 326},
		{121, 360},
		{78, 263},
		{75, 180},
		{269, 155},
		{-137, 488},
	},
	cities_control_positions = {
		{200, 200},
		{348, 326},
		{306, 321},
		{392, 375},
		{433, 390},
		{645, 540},
		{258, 425},
		{267, 440},
		{204, 370},
		{183, 351},
		{288, 333},
		{307, 563},
	},

	top_left = {150, 90},
	bottom_right = {320, 240},
})

atom('map_section.nz.sc.13w', {
	map = "images/map_zoom.png",
	cities = {
		'base::city.nz.17.home',
		'city.nz.sc.13w.chytri',
		'city.nz.sc.13w.ur',
		'city.nz.sc.13w.jerusalem',
		'city.nz.sc.13w.jericho',
		'city.nz.sc.13w.ashkelon',
		'city.nz.sc.13w.tyre',
		'city.nz.sc.13w.sidon',
		'city.nz.sc.13w.carchemish',
		'city.nz.sc.13w.alalakh',
		'city.nz.sc.13w.marhashi',
		'city.nz.sc.13w.mendes',
		'city.nz.sc.13w.heracleopolis_magna',
		'city.nz.sc.13w.der',
		'city.nz.sc.13w.susa',
		'city.nz.sc.13w.tarsus',
		'city.nz.sc.13w.adana',
		'city.nz.sc.13w.nineveh',
		'city.nz.sc.13w.assur',
		'city.nz.sc.13w.ecbatana',
	},
	cities_icon_positions = {
		{364, 359},
		{22, 258},
		{456, 451},
		{84, 390},
		{95, 384},
		{49, 397},
		{67, 354},
		{71, 336},
		{164, 197},
		{103, 220},
		{960, 592},
		{-96, 455},
		{-92, 520},
		{415, 333},
		{473, 367},
		{62, 194},
		{79, 189},
		{328, 206},
		{331, 233},
		{438, 262},
	},
	cities_label_positions = {
		{320, 357},
		{59, 265},
		{435, 451},
		{126, 405},
		{135, 384},
		{52, 422},
		{98, 357},
		{108, 337},
		{183, 177},
		{141, 222},
		{965, 567},
		{-96, 430},
		{-113, 549},
		{390, 335},
		{446, 367},
		{45, 172},
		{100, 168},
		{374, 209},
		{365, 237},
		{445, 240},
	},
	cities_control_positions = {
		{200, 200},
		{173, 378},
		{453, 384},
		{208, 446},
		{211, 423},
		{219, 469},
		{187, 408},
		{218, 383},
		{316, 244},
		{179, 342},
		{484, 754},
		{169, 511},
		{269, 561},
		{381, 332},
		{419, 339},
		{117, 364},
		{255, 237},
		{419, 249},
		{395, 273},
		{387, 279},
	},

	top_left = {150, 90},
	bottom_right = {320, 240},
})

-- Sargon DLC campaign
if array_contains(active_game_mods(), 'dlc_sargon') then
	--Sargon level 1
	atom_inherit('map_section.sargon.sc.1.section0', 'dlc_sargon::map_section.sargon.1.3.section0', {
		cities = {
			'dlc_sargon::city.sargon.1.home',
			'city.sargon.sc.1.babylon',
			'city.sargon.sc.1.der',
			'city.sargon.sc.1.nimrud',
			'city.sargon.sc.1.nineveh',
			'city.sargon.sc.1.memphis',
			'city.sargon.sc.1.qift',
			'city.sargon.sc.1.ecbatana',
			'city.sargon.sc.1.magan',
			'city.sargon.sc.1.hama',
			'city.sargon.sc.1.arpad',
			'city.sargon.sc.1.damascus',
			'city.sargon.sc.1.sumur',
			'city.sargon.sc.1.qarqar',
			'city.sargon.sc.1.gaza',
			'city.sargon.sc.1.rafah',
			'city.sargon.sc.1.gibeon',
		},
	})
	
	atom_inherit('map_section.sargon.sc.1w.section0', 'map_section.sargon.sc.1.section0', {
		cities = {
			'dlc_sargon::city.sargon.1.home',
			'city.sargon.sc.1w.babylon',
			'city.sargon.sc.1w.der',
			'city.sargon.sc.1w.nimrud',
			'city.sargon.sc.1w.nineveh',
			'city.sargon.sc.1w.memphis',
			'city.sargon.sc.1w.qift',
			'city.sargon.sc.1w.ecbatana',
			'city.sargon.sc.1w.magan',
			'city.sargon.sc.1w.hama',
			'city.sargon.sc.1w.arpad',
			'city.sargon.sc.1w.damascus',
			'city.sargon.sc.1w.sumur',
			'city.sargon.sc.1w.qarqar',
			'city.sargon.sc.1w.gaza',
			'city.sargon.sc.1w.rafah',
			'city.sargon.sc.1w.gibeon',
		},
	})
	
	--Sargon level 2
	atom_inherit('map_section.sargon.sc.2.section0', 'dlc_sargon::map_section.sargon.2.4.section0', {
		cities = {
			'dlc_sargon::city.sargon.2.home',
			'city.sargon.sc.2.hasanlu',
			'city.sargon.sc.2.izirtu',
			'city.sargon.sc.2.miandoab',
			'city.sargon.sc.2.saraba',
			'city.sargon.sc.2.assur',
			'city.sargon.sc.2.nimrud',
			'city.sargon.sc.2.corinth',
			'city.sargon.sc.2.salamis',
			'city.sargon.sc.2.babylon',
			'city.sargon.sc.2.nippur',
			'city.sargon.sc.2.marhashi',
			'city.sargon.sc.2.tanis',
			'city.sargon.sc.2.heracleopolis_magna',
			'city.sargon.sc.2.tabal',
			'city.sargon.sc.2.quwe',
			'city.sargon.sc.2.carchemish',
			'city.sargon.sc.2.til_barsip',
		},
	})
	
	atom_inherit('map_section.sargon.sc.2w.section0', 'map_section.sargon.sc.2.section0', {
		cities = {
			'dlc_sargon::city.sargon.2.home',
			'city.sargon.sc.2w.hasanlu',
			'city.sargon.sc.2w.izirtu',
			'city.sargon.sc.2w.miandoab',
			'city.sargon.sc.2w.saraba',
			'city.sargon.sc.2w.assur',
			'city.sargon.sc.2w.nimrud',
			'city.sargon.sc.2w.corinth',
			'city.sargon.sc.2w.salamis',
			'city.sargon.sc.2w.babylon',
			'city.sargon.sc.2w.nippur',
			'city.sargon.sc.2w.marhashi',
			'city.sargon.sc.2w.tanis',
			'city.sargon.sc.2w.heracleopolis_magna',
			'city.sargon.sc.2w.tabal',
			'city.sargon.sc.2w.quwe',
			'city.sargon.sc.2w.carchemish',
			'city.sargon.sc.2w.til_barsip',
		},
	})
	
	--Sargon level 3
	atom_inherit('map_section.sargon.sc.3.section0', 'dlc_sargon::map_section.sargon.3.4.section0', {
		cities = {
			'dlc_sargon::city.sargon.3.home',
			'city.sargon.sc.3.thebes',
			'city.sargon.sc.3.memphis',
			'city.sargon.sc.3.sais',
			'city.sargon.sc.3.magan',
			'city.sargon.sc.3.liblium',
			'city.sargon.sc.3.tarmakish',
			'city.sargon.sc.3.miandoab',
			'city.sargon.sc.3.saraba',
			'city.sargon.sc.3.quwe',
			'city.sargon.sc.3.adana',
			'city.sargon.sc.3.karatepe',
			'city.sargon.sc.3.gilzanu',
			'city.sargon.sc.3.gerdesorah',
			'city.sargon.sc.3.musasir',
			'city.sargon.sc.3.qallania',
			'city.sargon.sc.3.sippar',
			'city.sargon.sc.3.akkad',
			'city.sargon.sc.3.dur_kurigalzu',
			'city.sargon.sc.3.dur_abi_hara',
			'city.sargon.sc.3.babylon',
		},
	})
	
	atom_inherit('map_section.sargon.sc.3w.section0', 'map_section.sargon.sc.3.section0', {
		cities = {
			'dlc_sargon::city.sargon.3.home',
			'city.sargon.sc.3w.thebes',
			'city.sargon.sc.3w.memphis',
			'city.sargon.sc.3w.sais',
			'city.sargon.sc.3w.magan',
			'city.sargon.sc.3w.liblium',
			'city.sargon.sc.3w.tarmakish',
			'city.sargon.sc.3w.miandoab',
			'city.sargon.sc.3w.saraba',
			'city.sargon.sc.3w.quwe',
			'city.sargon.sc.3w.adana',
			'city.sargon.sc.3w.karatepe',
			'city.sargon.sc.3w.gilzanu',
			'city.sargon.sc.3w.gerdesorah',
			'city.sargon.sc.3w.musasir',
			'city.sargon.sc.3w.qallania',
			'city.sargon.sc.3w.sippar',
			'city.sargon.sc.3w.akkad',
			'city.sargon.sc.3w.dur_kurigalzu',
			'city.sargon.sc.3w.dur_abi_hara',
			'city.sargon.sc.3w.babylon',
		},
	})
	
	--Sargon level 4
	atom_inherit('map_section.sargon.sc.4.section0', 'dlc_sargon::map_section.sargon.4.4.section0', {
		cities = {
			'dlc_sargon::city.sargon.4.home',
			'city.sargon.sc.4.kish',
			'city.sargon.sc.4.sippar',
			'city.sargon.sc.4.sidon',
			'city.sargon.sc.4.tyre',
			'city.sargon.sc.4.bubastis',
			'city.sargon.sc.4.pelusium',
			'city.sargon.sc.4.susa',
			'city.sargon.sc.4.ecbatana',
			'city.sargon.sc.4.dur_yakin',
			'city.sargon.sc.4.nippur',
			'city.sargon.sc.4.isin',
			'city.sargon.sc.4.lagash',
			'city.sargon.sc.4.salamis',
			'city.sargon.sc.4.lapethos',
			'city.sargon.sc.4.amathus',
			'city.sargon.sc.4.marion',
			'city.sargon.sc.4.tabal',
			'city.sargon.sc.4.tuwana',
			'city.sargon.sc.4.hupisna',
		},
	})
	
	atom_inherit('map_section.sargon.sc.4w.section0', 'map_section.sargon.sc.4.section0', {
		cities = {
			'dlc_sargon::city.sargon.4.home',
			'city.sargon.sc.4w.kish',
			'city.sargon.sc.4w.sippar',
			'city.sargon.sc.4w.sidon',
			'city.sargon.sc.4w.tyre',
			'city.sargon.sc.4w.bubastis',
			'city.sargon.sc.4w.pelusium',
			'city.sargon.sc.4w.susa',
			'city.sargon.sc.4w.ecbatana',
			'city.sargon.sc.4w.dur_yakin',
			'city.sargon.sc.4w.nippur',
			'city.sargon.sc.4w.isin',
			'city.sargon.sc.4w.lagash',
			'city.sargon.sc.4w.salamis',
			'city.sargon.sc.4w.lapethos',
			'city.sargon.sc.4w.amathus',
			'city.sargon.sc.4w.marion',
			'city.sargon.sc.4w.tabal',
			'city.sargon.sc.4w.tuwana',
			'city.sargon.sc.4w.hupisna',
		},
	})
end