require("lua_functions")

--todo check if granary mod is loaded, add to allowed buildings if so

base_data = {
	base_mods = {"base"},
	first_residents_event = 'base::event.first_residents',
	leaving_residents_event = 'base::event.leaving_residents',
	returning_residents_event = 'base::event.returning_residents',
	no_path_residents_event = 'base::event.no_path_residents',
	no_path_trade_ship_event = 'base::event.no_path_trade_ship',
	festival_event = 'base::event.festival',
	god_wrath_event = 'base::event.god_wrath',
	color_configuration = 'base::color_configuration.base',
}

atom('mission.xtrade.1', base_data, {
	allowed_buildings = {
		'base::build.palm.1',
		'base::build.palm.2',
		'base::build.palm.3',
		'base::build.palm.4',
		'base::build.bush.1',
		'base::build.bush.2',
		'base::build.bush.3',
		'base::build.bush.4',
		'base::build.palm.bush.1',
		'base::build.palm.bush.2',
		'base::build.palm.bush.3',
		'base::build.palm.bush.4',
		'base::build.fish.1',
		'base::build.road.dirty',
		'base::build.road.stone',
		'base::build.road.decorative.1',
		'base::build.road.decorative.2',
		'base::build.road.decorative.3',
		'base::build.road.decorative.4',
		'base::build.road.decorative.5',
		'base::build.road.decorative.6',
		'base::build.road.decorative.7',
		'base::build.road.decorative.8',
		'base::build.road.decorative.9',
		'base::build.irrig.canal',
		'base::build.irrig.bridge.dirty',
		'base::build.irrig.bridge.stone',
		'base::build.irrig.bridge.decorative.1',
		'base::build.irrig.bridge.decorative.2',
		'base::build.irrig.bridge.decorative.3',
		'base::build.irrig.bridge.decorative.4',
		'base::build.irrig.bridge.decorative.5',
		'base::build.irrig.bridge.decorative.6',
		'base::build.irrig.bridge.decorative.7',
		'base::build.irrig.bridge.decorative.8',
		'base::build.irrig.bridge.decorative.9',
		'base::build.irrig.pump',
		'base::build.warehouse.13',
		'Granary::build.granary.13',
		'base::build.market.basic.7',
		'base::build.market.mid.11',
		'base::build.market.luxury.13',
		'base::build.risk.fire',
		'base::build.caravanserai.13',
		'base::build.farm.plant.13',
		'base::build.farm.animal.13',
		'base::build.shop.bread',
		'base::build.shop.ceramic',
		'base::build.shop.copper_jewels',
		'base::build.shop.brick',
		'base::build.shop.beer',
		'base::build.shop.tablet',
		'base::build.shop.ceremony',
		'base::build.shop.meat',
		'base::build.shop.furniture',
		'base::build.shop.gold_jewels',
		'base::build.shop.seal',
		'base::build.shop.fabric',
		'base::build.shop.cloth',
		'base::build.shop.ceramic_luxury',
		'base::build.shop.fabric_luxury',
		'base::build.shop.cloth_luxury',
		'base::build.shop.wine',
		'base::build.service.water',
		'base::build.service.priest',
		'base::build.service.administration',
		'base::build.service.library',
		'base::build.service.lawyer',
		'base::build.service.astrology',
		'base::build.risk.diseases.healer',
		'base::build.risk.diseases.hospital',
		'base::build.risk.crime',
		'base::build.mine.fish',
		'base::build.house.lower.4',
		'base::build.house.middle.5',
		'base::build.house.upper.5',
		'base::build.port.small',
		'base::build.port.big',
		'base::build.decor.grass',
		'base::build.decor.flowers.1',
		'base::build.decor.flowers.2',
		'base::build.decor.flowers.3',
		'base::build.decor.flowers.4',
		'base::build.decor.flowers.5',
		'base::build.decor.flowers.6',
		'base::build.decor.flowers.7',
		'base::build.decor.flowers.8',
		'base::build.decor.tree.1',
		'base::build.decor.tree.2',
		'base::build.decor.tree.3',
		'base::build.decor.tree.4',
		'base::build.decor.tree.5',
		'base::build.decor.tree.6',
		'base::build.decor.tree.7',
		'base::build.decor.tree.8',
		'base::build.decor.tree.9',
		'base::build.decor.tree.10',
		'base::build.decor.park.1',
		'base::build.decor.park.2',
		'base::build.decor.park.3',
		'base::build.decor.park.4',
		'base::build.decor.park.5',
		'base::build.decor.park.6',
		'base::build.decor.park.7',
		'base::build.decor.park.8',
		'base::build.decor.park.9',
		'base::build.decor.statue.eagle',
		'base::build.decor.statue.king.1',
		'base::build.decor.statue.king.2',
		'base::build.decor.statue.lion',
		'base::build.decor.statue.queen',
		'base::build.decor.statue.lamassu',
		'base::build.decor.statue.obelisk',
		'base::build.decor.statue.stele.1',
		'base::build.decor.statue.stele.2',
		'base::build.decor.statue.stele.3',
		'base::build.decor.statue.stele.4',
		'base::build.decor.statue.stele.5',
		'base::build.bridge',
		'base::build.square.1',
		'base::build.square.2',
		'base::build.square.3',
		'base::build.shrine.1',
		'base::build.shrine.2',
		'base::build.shrine.3',
		'base::build.shrine.4',
	},
	allowed_monuments = {
		'mn.temple.xtrade.1'
	},
	allowed_templates = {},
	target_money = 1000000,
	target_goods_atoms = {
		'base::goods.ceremony',
		'base::goods.copper',
		'base::goods.copper_jewels',
		'base::goods.gold',
		'base::goods.gold_jewels',
		'base::goods.ivory',
		'base::goods.seal',
		'base::goods.stone',
		'base::goods.wheat',
		'base::goods.wood',
	},
	target_goods_counts = {
		36,
		360,
		36,
		360,
		36,
		360,
		36,
		360,
		1440,
		360,
	},
	target_level_atoms = {
		'base::level.house.middle.5',
		'base::level.house.upper.5',
	},
	target_level_counts = {
		36,
		12,
	},
	target_monument_atoms = {
		'mn_category.temple.xtrade.1',
	},
	target_monument_counts = {
		1,
	},
	risks = 'risks.xtrade.sc.1',
	map = 'map.xtrade.sc.1',
	map_mod_override = 'expanded_trade_scenarios',
	prestige = 'prestige.xtrade.sc.1',
	description = 'description.xtrade.1',
	requests = {},
	demands = {},
	money_events = {},
})

atom('mission.xtrade.sc.1', base_data,  {
	allowed_buildings = {
		'base::build.palm.1',
		'base::build.palm.2',
		'base::build.palm.3',
		'base::build.palm.4',
		'base::build.bush.1',
		'base::build.bush.2',
		'base::build.bush.3',
		'base::build.bush.4',
		'base::build.palm.bush.1',
		'base::build.palm.bush.2',
		'base::build.palm.bush.3',
		'base::build.palm.bush.4',
		'base::build.fish.1',
		'base::build.road.dirty',
		'base::build.road.stone',
		'base::build.road.decorative.1',
		'base::build.road.decorative.2',
		'base::build.road.decorative.3',
		'base::build.road.decorative.4',
		'base::build.road.decorative.5',
		'base::build.road.decorative.6',
		'base::build.road.decorative.7',
		'base::build.road.decorative.8',
		'base::build.road.decorative.9',
		'base::build.irrig.canal',
		'base::build.irrig.bridge.dirty',
		'base::build.irrig.bridge.stone',
		'base::build.irrig.bridge.decorative.1',
		'base::build.irrig.bridge.decorative.2',
		'base::build.irrig.bridge.decorative.3',
		'base::build.irrig.bridge.decorative.4',
		'base::build.irrig.bridge.decorative.5',
		'base::build.irrig.bridge.decorative.6',
		'base::build.irrig.bridge.decorative.7',
		'base::build.irrig.bridge.decorative.8',
		'base::build.irrig.bridge.decorative.9',
		'base::build.irrig.pump',
		'base::build.warehouse.13',
		'Granary::build.granary.13',
		'base::build.market.basic.7',
		'base::build.market.mid.11',
		'base::build.market.luxury.13',
		'base::build.risk.fire',
		'base::build.caravanserai.13',
		'base::build.farm.plant.13',
		'base::build.farm.animal.13',
		'base::build.shop.bread',
		'base::build.shop.ceramic',
		'base::build.shop.copper_jewels',
		'base::build.shop.brick',
		'base::build.shop.beer',
		'base::build.shop.tablet',
		'base::build.shop.ceremony',
		'base::build.shop.meat',
		'base::build.shop.furniture',
		'base::build.shop.gold_jewels',
		'base::build.shop.seal',
		'base::build.shop.fabric',
		'base::build.shop.cloth',
		'base::build.shop.ceramic_luxury',
		'base::build.shop.fabric_luxury',
		'base::build.shop.cloth_luxury',
		'base::build.shop.wine',
		'base::build.service.water',
		'base::build.service.priest',
		'base::build.service.administration',
		'base::build.service.library',
		'base::build.service.lawyer',
		'base::build.service.astrology',
		'base::build.risk.diseases.healer',
		'base::build.risk.diseases.hospital',
		'base::build.risk.crime',
		'base::build.mine.fish',
		'base::build.house.lower.4',
		'base::build.house.middle.5',
		'base::build.house.upper.5',
		'base::build.port.small',
		'base::build.port.big',
		'base::build.decor.grass',
		'base::build.decor.flowers.1',
		'base::build.decor.flowers.2',
		'base::build.decor.flowers.3',
		'base::build.decor.flowers.4',
		'base::build.decor.flowers.5',
		'base::build.decor.flowers.6',
		'base::build.decor.flowers.7',
		'base::build.decor.flowers.8',
		'base::build.decor.tree.1',
		'base::build.decor.tree.2',
		'base::build.decor.tree.3',
		'base::build.decor.tree.4',
		'base::build.decor.tree.5',
		'base::build.decor.tree.6',
		'base::build.decor.tree.7',
		'base::build.decor.tree.8',
		'base::build.decor.tree.9',
		'base::build.decor.tree.10',
		'base::build.decor.park.1',
		'base::build.decor.park.2',
		'base::build.decor.park.3',
		'base::build.decor.park.4',
		'base::build.decor.park.5',
		'base::build.decor.park.6',
		'base::build.decor.park.7',
		'base::build.decor.park.8',
		'base::build.decor.park.9',
		'base::build.decor.statue.eagle',
		'base::build.decor.statue.king.1',
		'base::build.decor.statue.king.2',
		'base::build.decor.statue.lion',
		'base::build.decor.statue.queen',
		'base::build.decor.statue.lamassu',
		'base::build.decor.statue.obelisk',
		'base::build.decor.statue.stele.1',
		'base::build.decor.statue.stele.2',
		'base::build.decor.statue.stele.3',
		'base::build.decor.statue.stele.4',
		'base::build.decor.statue.stele.5',
		'base::build.bridge',
		'base::build.square.1',
		'base::build.square.2',
		'base::build.square.3',
		'base::build.shrine.1',
		'base::build.shrine.2',
		'base::build.shrine.3',
		'base::build.shrine.4',
	},
	allowed_monuments = {
		'base::mn.temple.sc',
		'base::mn.palace.sc',
	},
	allowed_templates = {
		'base::mn_template.temple.sc.5',
		'base::mn_template.palace.sc.5',
	},
	target_goods_atoms = {},
	target_goods_counts = {},
	target_level_atoms = {},
	target_level_counts = {},
	target_monument_atoms = {},
	target_monument_counts = {},
	risks = 'risks.xtrade.sc.1',
	map = 'map.xtrade.1',
	prestige = 'prestige.xtrade.sc.1',
	description = 'description.xtrade.1',
	requests = {},
	demands = {},
	money_events = {},
})